# ################################################################################
#  Copyright (c) 2025  Claudio André <portfolio-2025br at claudioandre.slmail.me>
#              ___                _      ___       _
#             (  _`\             ( )_  /'___)     (_ )  _
#             | |_) )  _    _ __ | ,_)| (__   _    | | (_)   _
#             | ,__/'/'_`\ ( '__)| |  | ,__)/'_`\  | | | | /'_`\
#             | |   ( (_) )| |   | |_ | |  ( (_) ) | | | |( (_) )
#             (_)   `\___/'(_)   `\__)(_)  `\___/'(___)(_)`\___/'
#
# This program comes with ABSOLUTELY NO WARRANTY; express or implied.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, as expressed in version 2, seen at
# https://www.gnu.org/licenses/gpl-2.0.html
# ################################################################################

---
name: Feature Request
description: Solicitar um novo recurso.
title: "[FEAT]: "
labels: ["enhancement"]

body:
  - type: markdown
    id: header
    attributes:
      value: |
        Obrigado por preencher esta solicitação de recurso.

  - type: textarea
    id: description
    attributes:
      label: Descrição
      description: Uma breve descrição do recurso.
      placeholder: |
        Forneça uma descrição clara e concisa do novo recurso que você gostaria de ver.
        Por exemplo: Sempre fico frustrado quando [...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Contexto
      description: Alternativas e contexto relevante.
      placeholder: |
        Forneça detalhes sobre soluções ou recursos alternativos que você tenha considerado.
        Adicione algum contexto sobre sua solicitação de recurso. Por exemplo, cole uma captura de tela ou forneça
        um link.
    validations:
      required: false
