# ################################################################################
#  Copyright (c) 2025  Claudio André <portfolio-2025br at claudioandre.slmail.me>
#              ___                _      ___       _
#             (  _`\             ( )_  /'___)     (_ )  _
#             | |_) )  _    _ __ | ,_)| (__   _    | | (_)   _
#             | ,__/'/'_`\ ( '__)| |  | ,__)/'_`\  | | | | /'_`\
#             | |   ( (_) )| |   | |_ | |  ( (_) ) | | | |( (_) )
#             (_)   `\___/'(_)   `\__)(_)  `\___/'(___)(_)`\___/'
#
# This program comes with ABSOLUTELY NO WARRANTY; express or implied.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, as expressed in version 2, seen at
# https://www.gnu.org/licenses/gpl-2.0.html
# ################################################################################
# GitHub Action to run some linters
# More info at https://github.com/portfolio-2025br/dotnet-simd

---
name: "Linter de Código"

"on":
  pull_request:
    branches: ["main"]
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: linter

    permissions:
      statuses: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            api.nuget.org:443
            api0.prismacloud.io:443
            checkpoint-api.hashicorp.com:443
            crl3.digicert.com:80
            github.com:443
            pypi.org:443
            raw.githubusercontent.com:443
            registry.terraform.io:443

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Linter
        uses: super-linter/super-linter@12150456a73e248bdc94d0794898f94e23127c88 # v7.4.0
        env:
          ENABLE_COMMITLINT_STRICT_MODE: true
          ENFORCE_COMMITLINT_CONFIGURATION_CHECK: true
          FIX_CSHARP: true
          FIX_MARKDOWN_PRETTIER: true
          FIX_YAML_PRETTIER: true
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check
        run: |
          echo "You should format source code properly!"
          echo "**********************************************************************"
          git diff
          echo "**********************************************************************"
          git diff --quiet
