# ################################################################################
#  Copyright (c) 2025  Claudio André <portfolio-2025br at claudioandre.slmail.me>
#              ___                _      ___       _
#             (  _`\             ( )_  /'___)     (_ )  _
#             | |_) )  _    _ __ | ,_)| (__   _    | | (_)   _
#             | ,__/'/'_`\ ( '__)| |  | ,__)/'_`\  | | | | /'_`\
#             | |   ( (_) )| |   | |_ | |  ( (_) ) | | | |( (_) )
#             (_)   `\___/'(_)   `\__)(_)  `\___/'(___)(_)`\___/'
#
# This program comes with ABSOLUTELY NO WARRANTY; express or implied.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, as expressed in version 2, seen at
# https://www.gnu.org/licenses/gpl-2.0.html
###############################################################################
# GitHub Action to react to PR reviews/comments and merge PRs on request
# More info at https://github.com/portfolio-2025br/dotnet-simd

---
name: Merge bot

"on":
  pull_request_review:
    types:
      - submitted
  issue_comment:
    types:
      - created

permissions:
  contents: read

jobs:
  call-merge-pr:
    permissions:
      contents: write
      pull-requests: write

    name: merge-bot-run
    if: >-
      startsWith(github.event.review.body, 'bot: MERGE') ||
      (
        github.event.issue.pull_request != '' &&
        startsWith(github.event.comment.body, 'bot: MERGE')
      )
    uses: portfolio-2025br/dotnet-simd/.github/workflows/merge-pr.yml@main
    with:
      branch: ${{ github.event.pull_request.head.ref }}
      owner: ${{ github.event.pull_request.head.repo.owner.login }}
      repo: ${{ github.event.pull_request.head.repo.name }}
      pr-number: ${{ github.event.pull_request.number || github.event.issue.number }}
      request: ${{ github.event.review.body || github.event.comment.body }}
