# ################################################################################
#  Copyright (c) 2025  Claudio André <portfolio-2025br at claudioandre.slmail.me>
#      ____              __                                _       _________  __
#     / __ )____  ____  / /__________ _____ ___  ____     | |     / / ____/ |/ /
#    / __  / __ \/ __ \/ __/ ___/ __ `/ __ `__ \/ __ \    | | /| / / __/  |   /
#   / /_/ / /_/ / /_/ / /_/ /__/ /_/ / / / / / / /_/ /    | |/ |/ / /___ /   |
#  /_____/\____/\____/\__/\___/\__,_/_/ /_/ /_/ .___/     |__/|__/_____//_/|_|
#                                            /_/
#
# This program comes with ABSOLUTELY NO WARRANTY; express or implied.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, as expressed in version 2, seen at
# https://www.gnu.org/licenses/gpl-2.0.html
# ################################################################################
# GitHub Action to close old issues automatically
# More info at https://github.com/portfolio-2025br/dotnet-simd

---
name: Close issues

"on":
  schedule:
    - cron: "30 1 * * *"

permissions:
  contents: read

jobs:
  close-issues:
    runs-on: ubuntu-latest
    name: stale

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443

      - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
        with:
          days-before-issue-stale: 14
          days-before-issue-close: 7
          exempt-issue-labels: "keep open,O: backlog"
          stale-issue-label: "O: stale"
          stale-issue-message: |
            "This issue is stale because it has been open for 14 days with no activity."
          close-issue-message: |
            "This issue was closed because it has been inactive for 7 days since being marked as stale."

          days-before-pr-stale: 14
          days-before-pr-close: -1
          exempt-pr-labels: "keep open"
          stale-pr-label: "O: stale"
          stale-pr-message: |
            "This PR is stale because it has been open for 14 days with no activity."

          # Avoid stale for specific milestones
          exempt-issue-milestones: "future"
          exempt-pr-milestones: "future"

          repo-token: ${{ secrets.GITHUB_TOKEN }}
